### PR TITLE
Fix loss of query-params and fragment on browser navigation

### PR DESCRIPTION
**Pull request by DrTom**
This is largely based on a patch by https://github.com/PEZ which has not
been merged.

### CODE REVIEW

**Comment by PEZ** [comment]
Are you going to pull this one, @venantius ?

**Comment by venantius** [comment]
I will, yes - sorry for the delay. I'll try to do it this weekend but am traveling today.

**Comment by iku000888** [comment]
(Sorry that I do not know much)

Just out of curiosity does this fix https://github.com/venantius/accountant/issues/19 as well, or unrelated?

**Comment by venantius** [comment]
@iku000888 I think this is unrelated.

**Pull request merged**
