### PR TITLE
Secretary 2

### PR DESCRIPTION
**Pull request by bago2k4**
Update Accountant to use Secretary 2.
As discussed [here](https://github.com/venantius/accountant/issues/2) i finally had a [response](https://github.com/gf3/secretary/issues/77#issuecomment-152267562) from the Secretary guys and i updated the library accordingly.
I have also added a build-transformer function that fix a 'bug' in the goog library: https://github.com/venantius/accountant/compare/venantius:master...bago2k4:secretary-2?expand=1#diff-df459cb347a6f7594df7019c7b1db3f9R63
Finally I have improved the check on the clicked ancor because before it was checking only the path, now i check for the domain to be empty or the same and if the target of the anchor is the same window, if not we shouldn't call `e.preventDefault()`.

I tried to maintain your coding style as much as possible, we should add some tests but now i don't have the time.

### CODE REVIEW

**Comment by venantius** [comment]
Going to need to rebase first, then I'll give this a more thorough review.

**Comment by bago2k4** [comment]
@venantius right, i'll rebase it tomorrow and then resolve the conflicts

**Comment by bago2k4** [comment]
closing this PR and opening a new one so we have a more clean commits history.

**Comment by venantius** [comment]
FYI, you can just force-push your branch and it'll update the PR with the new commit history.

**Comment by Seraf** [comment]
Hello @bago2k4, any news about the new PR please ?

Thanks for your work :)

**Pull request closed without merging**
