### PR TITLE
use custom url transformer to preserve hash and query params

### LINKED ISSUE #19: accountant/navigate! reuses existing query params, instead of resetting it
Here's a small scenario:

I have a search input. The input changes the URL in its `on-change` attribute. The URL is changed from:

`localhost:3449/` to `localhost:3449/?q=t`

But when I keep tying the word `test` into the search input, the URL changes to:

`localhost:3449/?q=t?q=te?q=tes?q=test`.

I have managed to track the issue down to this line in `core.cljs` line `108`:

```
(let [token (.getToken history)])
```

It seems the `Html5History` API from the Google Closure Library does not keep track/return the query string when calling `getToken` on it, because it always returns `"/"`, instead of `"/?q=t"` etc.

Is there any way I can work around this for now? I don't know if the issue is in the GCL `Html5History` API, or Accountant, or that I'm doing something wrong.

### PR DESCRIPTION
**Pull request by jalehman**
Ran into issue #19, and the PR (#24) that was submitted last year to fix it and #23.

It appears that there were some outstanding issues with that PR, and it appears to have been abandoned. This one incorporates that patch and resolves the issues that @venantius mentioned.

To summarize, this PR fixes #19 and #23, and incorporates the patches in PR #24.

### CODE REVIEW

**Comment by venantius** [comment]
I'm not doing too much work in ClojureScript these days. I assume you've confirmed that this works as expected?

**Comment by jalehman** [comment]
I actually just discovered that it correctly avoided duplication of query params and preserved the hash in back events, **however** it did not preserve the **query params** in back events.

I've fixed the issue locally -- would you prefer an additional commit in this PR, or a new PR with one commit?

**Comment by venantius** [comment]
Feel free to add it to this PR.

**Comment by jalehman** [comment]
Thanks!

**Comment by jalehman** [comment]
Doh. Forgot about an earlier commit.

**Comment by venantius** [comment]
you know you can just force-push to your branch and it'll update this PR, right?

**Comment by jalehman** [comment]
That would have been way smarter. Think I screwed things over now by rushing to a poor solution (branch deleted and recreated on GH).

**Pull request closed without merging**
