### PR TITLE
fix: port number

### PR DESCRIPTION
**Pull request by nicorikken**
The fix proposed in https://github.com/venantius/accountant/pull/35 was too
rigorous. Relative URLs lack a port number, and thus a link on a domain with a
port triggers a reload. This is not efficient.

This fix resolves this issue by only executing the check in case a port number
is specified in the link. Other checks on the domain to ensure proper reloeads
are already cared for.

Ports are compared as strings, to avoid any type issues.

### CODE REVIEW

**Comment by nicorikken** [comment]
Sorry, I tested the functionality I desired on my last PR, not the existing functionality. This should fix things. Perhaps some testcases would be nice.

I have verified that this fix is working, with:
- Firefox `51.0.1 (64-bit)`
- Chromium `Version 58.0.2999.0 (64-bit)`
- Safari `Version 10.0 (11602.1.50.0.10)`

**Comment by venantius** [comment]
I'll try to get a new release of this out this evening. Feel free to remind me if I forget.

**Comment by edvorg** [comment]
Hi. How is it going with releasing a new version @venantius ?

**Comment by venantius** [comment]
0.1.9 is now up on Clojars.

**Comment by edvorg** [comment]
Cool, thank you so much!

**Pull request merged**
